// Arabic titles for the sidebar/nav, keyed by section slug.
// Falls back to the English title (from lib/sections.ts) when a slug is missing here.
export const sectionTitlesAr: Record<string, string> = {
  "course-introduction": "مقدمة الكورس",
  "development-environment-setup": "إعداد بيئة التطوير",
  "next-js-fundamentals": "أساسيات Next.js",
  "app-router-basics": "أساسيات App Router",
  "navigation-and-routing": "التنقل والتوجيه",
  "server-components-and-client-components": "مكونات السيرفر والعميل",
  "styling-in-next-js": "التنسيق في Next.js",
  "assets-images-and-metadata": "الأصول والصور والبيانات الوصفية",
  "data-fetching": "جلب البيانات",
  "caching-and-revalidation": "التخزين المؤقت وإعادة التحقق",
  "forms-and-server-actions": "النماذج و Server Actions",
  "route-handlers-and-apis": "معالجات المسارات وواجهات API",
  "error-handling": "معالجة الأخطاء",
  authentication: "المصادقة",
  "middleware-and-proxy": "الوسيط (Middleware) والبروكسي",
  "database-integration": "ربط قواعد البيانات",
  "state-management": "إدارة الحالة",
  "performance-optimization": "تحسين الأداء",
  "seo-and-production-readiness": "تهيئة SEO والإنتاج",
  deployment: "النشر",
  "project-blog-app": "مشروع: تطبيق مدونة",
  "project-dashboard-app": "مشروع: لوحة تحكم",
  "project-full-stack-crud-app": "مشروع: تطبيق CRUD متكامل",
  "project-mini-e-commerce-app": "مشروع: متجر إلكتروني مصغر",
  "final-review-and-next-steps": "المراجعة النهائية والخطوات القادمة",
};
